pokemonTypeTable = {
  {name = "Bulbasaur", type1 = "Grass", type2 = "Poison"},
  {name = "Ivysaur", type1 = "Grass", type2 = "Poison"},
  {name = "Venusaur", type1 = "Grass", type2 = "Poison"},
  {name = "Charmander", type1 = "Fire", type2 = nil},
  {name = "Charmeleon", type1 = "Fire", type2 = nil},
  {name = "Charizard", type1 = "Fire", type2 = "Flying"},
  {name = "Squirtle", type1 = "Water", type2 = nil},
  {name = "Wartortle", type1 = "Water", type2 = nil},
  {name = "Blastoise", type1 = "Water", type2 = nil},
  {name = "Caterpie", type1 = "Bug", type2 = nil},
  {name = "Metapod", type1 = "Bug", type2 = nil},
  {name = "Butterfree", type1 = "Bug", type2 = "Flying"},
  {name = "Weedle", type1 = "Bug", type2 = "Poison"},
  {name = "Kakuna", type1 = "Bug", type2 = "Poison"},
  {name = "Beedrill", type1 = "Bug", type2 = "Poison"},
  {name = "Pidgey", type1 = "Normal", type2 = "Flying"},
  {name = "Pidgeotto", type1 = "Normal", type2 = "Flying"},
  {name = "Pidgeot", type1 = "Normal", type2 = "Flying"},
  {name = "Rattata", type1 = "Normal", type2 = nil},
  {name = "Raticate", type1 = "Normal", type2 = nil},
  {name = "Spearow", type1 = "Normal", type2 = "Flying"},
  {name = "Fearow", type1 = "Normal", type2 = "Flying"},
  {name = "Ekans", type1 = "Poison", type2 = nil},
  {name = "Arbok", type1 = "Poison", type2 = nil},
  {name = "Pikachu", type1 = "Electric", type2 = nil},
  {name = "Raichu", type1 = "Electric", type2 = nil},
  {name = "Sandshrew", type1 = "Ground", type2 = nil},
  {name = "Sandslash", type1 = "Ground", type2 = nil},
  {name = "Nidoran female", type1 = "Poison", type2 = nil},
  {name = "Nidorina", type1 = "Poison", type2 = nil},
  {name = "Nidoqueen", type1 = "Poison", type2 = "Ground"},
  {name = "Nidoran male", type1 = "Poison", type2 = nil},
  {name = "Nidorino", type1 = "Poison", type2 = nil},
  {name = "Nidoking", type1 = "Poison", type2 = "Ground"},
  {name = "Clefairy", type1 = "Fairy", type2 = nil},
  {name = "Clefable", type1 = "Fairy", type2 = nil },
  {name = "Vulpix", type1 = "Fire", type2 = nil },
  {name = "Ninetales", type1 = "Fire", type2 = nil },
  {name = "Jigglypuff", type1 = "Normal", type2 = "Fairy" },
  {name = "Wigglytuff", type1 = "Normal", type2 = "Fairy" },
  {name = "Zubat", type1 = "Poison", type2 = "Flying" },
  {name = "Golbat", type1 = "Poison", type2 = "Flying" },
  {name = "Oddish", type1 = "Grass", type2 = "Poison" },
  {name = "Gloom", type1 = "Grass", type2 = "Poison" },
  {name = "Vileplume", type1 = "Grass", type2 = "Poison" },
  {name = "Paras", type1 = "Bug", type2 = "Grass" },
  {name = "Parasect", type1 = "Bug", type2 = "Grass" },
  {name = "Venonat", type1 = "Bug", type2 = "Poison" },
  {name = "Venomoth", type1 = "Bug", type2 = "Poison" },
  {name = "Diglett", type1 = "Ground", type2 = nil },
  {name = "Dugtrio", type1 = "Ground", type2 = nil },
  {name = "Meowth", type1 = "Normal", type2 = nil },
  {name = "Persian", type1 = "Normal", type2 = nil },
  {name = "Psyduck", type1 = "Water", type2 = nil },
  {name = "Golduck", type1 = "Water", type2 = nil },
  {name = "Mankey", type1 = "Fighting", type2 = nil },
  {name = "Primeape", type1 = "Fighting", type2 = nil },
  {name = "Growlithe", type1 = "Fire", type2 = nil },
  {name = "Arcanine", type1 = "Fire", type2 = nil },
  {name = "Poliwag", type1 = "Water", type2 = nil },
  {name = "Poliwhirl", type1 = "Water", type2 = nil },
  {name = "Poliwrath", type1 = "Water", type2 = "Fighting" },
  {name = "Abra", type1 = "Psychic", type2 = nil },
  {name = "Kadabra", type1 = "Psychic", type2 = nil },
  {name = "Alakazam", type1 = "Psychic", type2 = nil },
  {name = "Machop", type1 = "Fighting", type2 = nil },
  {name = "Machoke", type1 = "Fighting", type2 = nil },
  {name = "Machamp", type1 = "Fighting", type2 = nil },
  {name = "Bellsprout", type1 = "Grass", type2 = "Poison" },
  {name = "Weepinbell", type1 = "Grass", type2 = "Poison" },
  {name = "Victreebel", type1 = "Grass", type2 = "Poison" },
  {name = "Tentacool", type1 = "Water", type2 = "Poison" },
  {name = "Tentacruel", type1 = "Water", type2 = "Poison" },
  {name = "Geodude", type1 = "Rock", type2 = "Ground" },
  {name = "Graveler", type1 = "Rock", type2 = "Ground" },
  {name = "Golem", type1 = "Rock", type2 = "Ground" },
  {name = "Ponyta", type1 = "Fire", type2 = nil },
  {name = "Rapidash", type1 = "Fire", type2 = nil },
  {name = "Slowpoke", type1 = "Water", type2 = "Psychic" },
  {name = "Slowbro", type1 = "Water", type2 = "Psychic" },
  {name = "Magnemite", type1 = "Electric", type2 = "Steel" },
  {name = "Magneton", type1 = "Electric", type2 = "Steel" },
  {name = "Farfetch'd", type1 = "Normal", type2 = "Flying" },
  {name = "Doduo", type1 = "Normal", type2 = "Flying" },
  {name = "Dodrio", type1 = "Normal", type2 = "Flying" },
  {name = "Seel", type1 = "Water", type2 = nil },
  {name = "Dewgong", type1 = "Water", type2 = "Ice" },
  {name = "Grimer", type1 = "Poison", type2 = nil },
  {name = "Muk", type1 = "Poison", type2 = nil },
  {name = "Shellder", type1 = "Water", type2 = nil },
  {name = "Cloyster", type1 = "Water", type2 = "Ice" },
  {name = "Gastly", type1 = "Ghost", type2 = "Poison" },
  {name = "Haunter", type1 = "Ghost", type2 = "Poison" },
  {name = "Gengar", type1 = "Ghost", type2 = "Poison" },
  {name = "Onix", type1 = "Rock", type2 = "Ground" },
  {name = "Drowzee", type1 = "Psychic", type2 = nil },
  {name = "Hypno", type1 = "Psychic", type2 = nil },
  {name = "Krabby", type1 = "Water", type2 = nil },
  {name = "Kingler", type1 = "Water", type2 = nil },
  {name = "Voltorb", type1 = "Electric", type2 = nil },
  {name = "Electrode", type1 = "Electric", type2 = nil },
  {name = "Exeggcute", type1 = "Grass", type2 = "Psychic" },
  {name = "Exeggutor", type1 = "Grass", type2 = "Psychic" },
  {name = "Cubone", type1 = "Ground", type2 = nil },
  {name = "Marowak", type1 = "Ground", type2 = nil },
  {name = "Hitmonlee", type1 = "Fighting", type2 = nil },
  {name = "Hitmonchan", type1 = "Fighting", type2 = nil },
  {name = "Lickitung", type1 = "Normal", type2 = nil },
  {name = "Koffing", type1 = "Poison", type2 = nil },
  {name = "Weezing", type1 = "Poison", type2 = nil },
  {name = "Rhyhorn", type1 = "Ground", type2 = "Rock" },
  {name = "Rhydon", type1 = "Ground", type2 = "Rock" },
  {name = "Chansey", type1 = "Normal", type2 = nil },
  {name = "Tangela", type1 = "Grass", type2 = nil },
  {name = "Kangaskhan", type1 = "Normal", type2 = nil },
  {name = "Horsea", type1 = "Water", type2 = nil },
  {name = "Seadra", type1 = "Water", type2 = nil },
  {name = "Goldeen", type1 = "Water", type2 = nil },
  {name = "Seaking", type1 = "Water", type2 = nil },
  {name = "Staryu", type1 = "Water", type2 = nil },
  {name = "Starmie", type1 = "Water", type2 = "Psychic" },
  {name = "Mr. Mime", type1 = "Psychic", type2 = "Fairy" },
  {name = "Scyther", type1 = "Bug", type2 = "Flying" },
  {name = "Jynx", type1 = "Ice", type2 = "Psychic" },
  {name = "Electabuzz", type1 = "Electric", type2 = nil },
  {name = "Magmar", type1 = "Fire", type2 = nil },
  {name = "Pinsir", type1 = "Bug", type2 = nil },
  {name = "Tauros", type1 = "Normal", type2 = nil },
  {name = "Magikarp", type1 = "Water", type2 = nil },
  {name = "Gyarados", type1 = "Water", type2 = "Flying" },
  {name = "Lapras", type1 = "Water", type2 = "Ice" },
  {name = "Ditto", type1 = "Normal", type2 = nil },
  {name = "Eevee", type1 = "Normal", type2 = nil },
  {name = "Vaporeon", type1 = "Water", type2 = nil },
  {name = "Jolteon", type1 = "Electric", type2 = nil },
  {name = "Flareon", type1 = "Fire", type2 = nil },
  {name = "Porygon", type1 = "Normal", type2 = nil },
  {name = "Omanyte", type1 = "Rock", type2 = "Water" },
  {name = "Omastar", type1 = "Rock", type2 = "Water" },
  {name = "Kabuto", type1 = "Rock", type2 = "Water" },
  {name = "Kabutops", type1 = "Rock", type2 = "Water" },
  {name = "Aerodactyl", type1 = "Rock", type2 = "Flying" },
  {name = "Snorlax", type1 = "Normal", type2 = nil },
  {name = "Articuno", type1 = "Ice", type2 = "Flying" },
  {name = "Zapdos", type1 = "Electric", type2 = "Flying" },
  {name = "Moltres", type1 = "Fire", type2 = "Flying" },
  {name = "Dratini", type1 = "Dragon", type2 = nil },
  {name = "Dragonair", type1 = "Dragon", type2 = nil },
  {name = "Dragonite", type1 = "Dragon", type2 = "Flying" },
  {name = "Mewtwo", type1 = "Psychic", type2 = nil },
  {name = "Mew", type1 = "Psychic", type2 = nil },
  {name = "Chikorita", type1 = "Grass", type2 = nil },
  {name = "Bayleef", type1 = "Grass", type2 = nil },
  {name = "Meganium", type1 = "Grass", type2 = nil },
  {name = "Cyndaquil", type1 = "Fire", type2 = nil },
  {name = "Quilava", type1 = "Fire", type2 = nil },
  {name = "Typhlosion", type1 = "Fire", type2 = nil },
  {name = "Totodile", type1 = "Water", type2 = nil },
  {name = "Croconaw", type1 = "Water", type2 = nil },
  {name = "Feraligatr", type1 = "Water", type2 = nil },
  {name = "Sentret", type1 = "Normal", type2 = nil },
  {name = "Furret", type1 = "Normal", type2 = nil },
  {name = "Hoothoot", type1 = "Normal", type2 = "Flying" },
  {name = "Noctowl", type1 = "Normal", type2 = "Flying" },
  {name = "Ledyba", type1 = "Bug", type2 = "Flying" },
  {name = "Ledian", type1 = "Bug", type2 = "Flying" },
  {name = "Spinarak", type1 = "Bug", type2 = "Poison" },
  {name = "Ariados", type1 = "Bug", type2 = "Poison" },
  {name = "Crobat", type1 = "Poison", type2 = "Flying" },
  {name = "Chinchou", type1 = "Water", type2 = "Electric" },
  {name = "Lanturn", type1 = "Water", type2 = "Electric" },
  {name = "Pichu", type1 = "Electric", type2 = nil },
  {name = "Cleffa", type1 = "Fairy", type2 = nil },
  {name = "Igglybuff", type1 = "Normal", type2 = "Fairy" },
  {name = "Togepi", type1 = "Fairy", type2 = nil },
  {name = "Togetic", type1 = "Fairy", type2 = "Flying" },
  {name = "Natu", type1 = "Psychic", type2 = "Flying" },
  {name = "Xatu", type1 = "Psychic", type2 = "Flying" },
  {name = "Mareep", type1 = "Electric", type2 = nil },
  {name = "Flaaffy", type1 = "Electric", type2 = nil },
  {name = "Ampharos", type1 = "Electric", type2 = nil },
  {name = "Bellossom", type1 = "Grass", type2 = nil },
  {name = "Marill", type1 = "Water", type2 = "Fairy" },
  {name = "Azumarill", type1 = "Water", type2 = "Fairy" },
  {name = "Sudowoodo", type1 = "Rock", type2 = nil },
  {name = "Politoed", type1 = "Water", type2 = nil },
  {name = "Hoppip", type1 = "Grass", type2 = "Flying" },
  {name = "Skiploom", type1 = "Grass", type2 = "Flying" },
  {name = "Jumpluff", type1 = "Grass", type2 = "Flying" },
  {name = "Aipom", type1 = "Normal", type2 = nil },
  {name = "Sunkern", type1 = "Grass", type2 = nil },
  {name = "Sunflora", type1 = "Grass", type2 = nil },
  {name = "Yanma", type1 = "Bug", type2 = "Flying" },
  {name = "Wooper", type1 = "Water", type2 = "Ground" },
  {name = "Quagsire", type1 = "Water", type2 = "Ground" },
  {name = "Espeon", type1 = "Psychic", type2 = nil },
  {name = "Umbreon", type1 = "Dark", type2 = nil },
  {name = "Murkrow", type1 = "Dark", type2 = "Flying" },
  {name = "Slowking", type1 = "Water", type2 = "Psychic" },
  {name = "Misdreavus", type1 = "Ghost", type2 = nil },
  {name = "Unown", type1 = "Psychic", type2 = nil },
  {name = "Wobbuffet", type1 = "Psychic", type2 = nil },
  {name = "Girafarig", type1 = "Normal", type2 = "Psychic" },
  {name = "Pineco", type1 = "Bug", type2 = nil },
  {name = "Forretress", type1 = "Bug", type2 = "Steel" },
  {name = "Dunsparce", type1 = "Normal", type2 = nil },
  {name = "Gligar", type1 = "Ground", type2 = "Flying" },
  {name = "Steelix", type1 = "Steel", type2 = "Ground" },
  {name = "Snubbull", type1 = "Fairy", type2 = nil },
  {name = "Granbull", type1 = "Fairy", type2 = nil },
  {name = "Qwilfish", type1 = "Water", type2 = "Poison" },
  {name = "Scizor", type1 = "Bug", type2 = "Steel" },
  {name = "Shuckle", type1 = "Bug", type2 = "Rock" },
  {name = "Heracross", type1 = "Bug", type2 = "Fighting" },
  {name = "Sneasel", type1 = "Dark", type2 = "Ice" },
  {name = "Teddiursa", type1 = "Normal", type2 = nil },
  {name = "Ursaring", type1 = "Normal", type2 = nil },
  {name = "Slugma", type1 = "Fire", type2 = nil },
  {name = "Magcargo", type1 = "Fire", type2 = "Rock" },
  {name = "Swinub", type1 = "Ice", type2 = "Ground" },
  {name = "Piloswine", type1 = "Ice", type2 = "Ground" },
  {name = "Corsola", type1 = "Ghost", type2 = nil },
  {name = "Delibird", type1 = "Ice", type2 = "Flying" },
  {name = "Mantine", type1 = "Water", type2 = "Flying" },
  {name = "Skarmory", type1 = "Steel", type2 = "Flying" },
  {name = "Houndour", type1 = "Dark", type2 = "Fire" },
  {name = "Houndoom", type1 = "Dark", type2 = "Fire" },
  {name = "Kingdra", type1 = "Water", type2 = "Dragon" },
  {name = "Phanpy", type1 = "Ground", type2 = nil },
  {name = "Donphan", type1 = "Ground", type2 = nil },
  {name = "Porygon2", type1 = "Normal", type2 = nil },
  {name = "Stantler", type1 = "Normal", type2 = nil },
  {name = "Smeargle", type1 = "Normal", type2 = nil },
  {name = "Tyrogue", type1 = "Fighting", type2 = nil },
  {name = "Hitmontop", type1 = "Fighting", type2 = nil },
  {name = "Smoochum", type1 = "Ice", type2 = "Psychic" },
  {name = "Elekid", type1 = "Electric", type2 = nil },
  {name = "Magby", type1 = "Fire", type2 = nil },
  {name = "Miltank", type1 = "Normal", type2 = nil },
  {name = "Blissey", type1 = "Normal", type2 = nil },
  {name = "Raikou", type1 = "Electric", type2 = nil },
  {name = "Entei", type1 = "Fire", type2 = nil },
  {name = "Suicune", type1 = "Water", type2 = nil },
  {name = "Larvitar", type1 = "Rock", type2 = "Ground" },
  {name = "Pupitar", type1 = "Rock", type2 = "Ground" },
  {name = "Tyranitar", type1 = "Rock", type2 = "Dark" },
  {name = "Lugia", type1 = "Psychic", type2 = "Flying" },
  {name = "Ho-Oh", type1 = "Fire", type2 = "Flying" },
  {name = "Celebi", type1 = "Psychic", type2 = "Grass" },
  {name = "Treecko", type1 = "Grass", type2 = nil },
  {name = "Grovyle", type1 = "Grass", type2 = nil },
  {name = "Sceptile", type1 = "Grass", type2 = nil },
  {name = "Torchic", type1 = "Fire", type2 = nil },
  {name = "Combusken", type1 = "Fire", type2 = "Fighting" },
  {name = "Blaziken", type1 = "Fire", type2 = "Fighting" },
  {name = "Mudkip", type1 = "Water", type2 = nil },
  {name = "Marshtomp", type1 = "Water", type2 = "Ground" },
  {name = "Swampert", type1 = "Water", type2 = "Ground" },
  {name = "Poochyena", type1 = "Dark", type2 = nil },
  {name = "Mightyena", type1 = "Dark", type2 = nil },
  {name = "Zigzagoon", type1 = "Normal", type2 = nil },
  {name = "Linoone", type1 = "Normal", type2 = nil },
  {name = "Wurmple", type1 = "Bug", type2 = nil },
  {name = "Silcoon", type1 = "Bug", type2 = nil },
  {name = "Beautifly", type1 = "Bug", type2 = "Flying" },
  {name = "Cascoon", type1 = "Bug", type2 = nil },
  {name = "Dustox", type1 = "Bug", type2 = "Poison" },
  {name = "Lotad", type1 = "Water", type2 = "Grass" },
  {name = "Lombre", type1 = "Water", type2 = "Grass" },
  {name = "Ludicolo", type1 = "Water", type2 = "Grass" },
  {name = "Seedot", type1 = "Grass", type2 = nil },
  {name = "Nuzleaf", type1 = "Grass", type2 = "Dark" },
  {name = "Shiftry", type1 = "Grass", type2 = "Dark" },
  {name = "Taillow", type1 = "Normal", type2 = "Flying" },
  {name = "Swellow", type1 = "Normal", type2 = "Flying" },
  {name = "Wingull", type1 = "Water", type2 = "Flying" },
  {name = "Pelipper", type1 = "Water", type2 = "Flying" },
  {name = "Ralts", type1 = "Psychic", type2 = "Fairy" },
  {name = "Kirlia", type1 = "Psychic", type2 = "Fairy" },
  {name = "Gardevoir", type1 = "Psychic", type2 = "Fairy" },
  {name = "Surskit", type1 = "Bug", type2 = "Water" },
  {name = "Masquerain", type1 = "Bug", type2 = "Flying" },
  {name = "Shroomish", type1 = "Grass", type2 = nil },
  {name = "Breloom", type1 = "Grass", type2 = "Fighting" },
  {name = "Slakoth", type1 = "Normal", type2 = nil },
  {name = "Vigoroth", type1 = "Normal", type2 = nil },
  {name = "Slaking", type1 = "Normal", type2 = nil },
  {name = "Nincada", type1 = "Bug", type2 = "Ground" },
  {name = "Ninjask", type1 = "Bug", type2 = "Flying" },
  {name = "Shedinja", type1 = "Bug", type2 = "Ghost" },
  {name = "Whismur", type1 = "Normal", type2 = nil },
  {name = "Loudred", type1 = "Normal", type2 = nil },
  {name = "Exploud", type1 = "Normal", type2 = nil },
  {name = "Makuhita", type1 = "Fighting", type2 = nil },
  {name = "Hariyama", type1 = "Fighting", type2 = nil },
  {name = "Azurill", type1 = "Normal", type2 = "Fairy" },
  {name = "Nosepass", type1 = "Rock", type2 = nil },
  {name = "Skitty", type1 = "Normal", type2 = nil },
  {name = "Delcatty", type1 = "Normal", type2 = nil },
  {name = "Sableye", type1 = "Dark", type2 = "Ghost" },
  {name = "Mawile", type1 = "Steel", type2 = "Fairy" },
  {name = "Aron", type1 = "Steel", type2 = "Rock" },
  {name = "Lairon", type1 = "Steel", type2 = "Rock" },
  {name = "Aggron", type1 = "Steel", type2 = "Rock" },
  {name = "Meditite", type1 = "Fighting", type2 = "Psychic" },
  {name = "Medicham", type1 = "Fighting", type2 = "Psychic" },
  {name = "Electrike", type1 = "Electric", type2 = nil },
  {name = "Manectric", type1 = "Electric", type2 = nil },
  {name = "Plusle", type1 = "Electric", type2 = nil },
  {name = "Minun", type1 = "Electric", type2 = nil },
  {name = "Volbeat", type1 = "Bug", type2 = nil },
  {name = "Illumise", type1 = "Bug", type2 = nil },
  {name = "Roselia", type1 = "Grass", type2 = "Poison" },
  {name = "Gulpin", type1 = "Poison", type2 = nil },
  {name = "Swalot", type1 = "Poison", type2 = nil },
  {name = "Carvanha", type1 = "Water", type2 = "Dark" },
  {name = "Sharpedo", type1 = "Water", type2 = "Dark" },
  {name = "Wailmer", type1 = "Water", type2 = nil },
  {name = "Wailord", type1 = "Water", type2 = nil },
  {name = "Numel", type1 = "Fire", type2 = "Ground" },
  {name = "Camerupt", type1 = "Fire", type2 = "Ground" },
  {name = "Torkoal", type1 = "Fire", type2 = nil },
  {name = "Spoink", type1 = "Psychic", type2 = nil },
  {name = "Grumpig", type1 = "Psychic", type2 = nil },
  {name = "Spinda", type1 = "Normal", type2 = nil },
  {name = "Trapinch", type1 = "Ground", type2 = nil },
  {name = "Vibrava", type1 = "Ground", type2 = "Dragon" },
  {name = "Flygon", type1 = "Ground", type2 = "Dragon" },
  {name = "Cacnea", type1 = "Grass", type2 = nil },
  {name = "Cacturne", type1 = "Grass", type2 = "Dark" },
  {name = "Swablu", type1 = "Normal", type2 = "Flying" },
  {name = "Altaria", type1 = "Dragon", type2 = "Flying" },
  {name = "Zangoose", type1 = "Normal", type2 = nil },
  {name = "Seviper", type1 = "Poison", type2 = nil },
  {name = "Lunatone", type1 = "Rock", type2 = "Psychic" },
  {name = "Solrock", type1 = "Rock", type2 = "Psychic" },
  {name = "Barboach", type1 = "Water", type2 = "Ground" },
  {name = "Whiscash", type1 = "Water", type2 = "Ground" },
  {name = "Corphish", type1 = "Water", type2 = nil },
  {name = "Crawdaunt", type1 = "Water", type2 = "Dark" },
  {name = "Baltoy", type1 = "Ground", type2 = "Psychic" },
  {name = "Claydol", type1 = "Ground", type2 = "Psychic" },
  {name = "Lileep", type1 = "Rock", type2 = "Grass" },
  {name = "Cradily", type1 = "Rock", type2 = "Grass" },
  {name = "Anorith", type1 = "Rock", type2 = "Bug" },
  {name = "Armaldo", type1 = "Rock", type2 = "Bug" },
  {name = "Feebas", type1 = "Water", type2 = nil },
  {name = "Milotic", type1 = "Water", type2 = nil },
  {name = "Castform", type1 = "Normal", type2 = nil },
  {name = "Kecleon", type1 = "Normal", type2 = nil },
  {name = "Shuppet", type1 = "Ghost", type2 = nil },
  {name = "Banette", type1 = "Ghost", type2 = nil },
  {name = "Duskull", type1 = "Ghost", type2 = nil },
  {name = "Dusclops", type1 = "Ghost", type2 = nil },
  {name = "Tropius", type1 = "Grass", type2 = "Flying" },
  {name = "Chimecho", type1 = "Psychic", type2 = nil },
  {name = "Absol", type1 = "Dark", type2 = nil },
  {name = "Wynaut", type1 = "Psychic", type2 = nil },
  {name = "Snorunt", type1 = "Ice", type2 = nil },
  {name = "Glalie", type1 = "Ice", type2 = nil },
  {name = "Spheal", type1 = "Ice", type2 = "Water" },
  {name = "Sealeo", type1 = "Ice", type2 = "Water" },
  {name = "Walrein", type1 = "Ice", type2 = "Water" },
  {name = "Clamperl", type1 = "Water", type2 = nil },
  {name = "Huntail", type1 = "Water", type2 = nil },
  {name = "Gorebyss", type1 = "Water", type2 = nil },
  {name = "Relicanth", type1 = "Water", type2 = "Rock" },
  {name = "Luvdisc", type1 = "Water", type2 = nil },
  {name = "Bagon", type1 = "Dragon", type2 = nil },
  {name = "Shelgon", type1 = "Dragon", type2 = nil },
  {name = "Salamence", type1 = "Dragon", type2 = "Flying" },
  {name = "Beldum", type1 = "Steel", type2 = "Psychic" },
  {name = "Metang", type1 = "Steel", type2 = "Psychic" },
  {name = "Metagross", type1 = "Steel", type2 = "Psychic" },
  {name = "Regirock", type1 = "Rock", type2 = nil },
  {name = "Regice", type1 = "Ice", type2 = nil },
  {name = "Registeel", type1 = "Steel", type2 = nil },
  {name = "Latias", type1 = "Dragon", type2 = "Psychic" },
  {name = "Latios", type1 = "Dragon", type2 = "Psychic" },
  {name = "Kyogre", type1 = "Water", type2 = nil },
  {name = "Groudon", type1 = "Ground", type2 = nil },
  {name = "Rayquaza", type1 = "Dragon", type2 = "Flying" },
  {name = "Jirachi", type1 = "Steel", type2 = "Psychic" },
  {name = "Deoxys", type1 = "Psychic", type2 = nil },
  {name = "Turtwig", type1 = "Grass", type2 = nil },
  {name = "Grotle", type1 = "Grass", type2 = nil },
  {name = "Torterra", type1 = "Grass", type2 = "Ground" },
  {name = "Chimchar", type1 = "Fire", type2 = nil },
  {name = "Monferno", type1 = "Fire", type2 = "Fighting" },
  {name = "Infernape", type1 = "Fire", type2 = "Fighting" },
  {name = "Piplup", type1 = "Water", type2 = nil },
  {name = "Prinplup", type1 = "Water", type2 = nil },
  {name = "Empoleon", type1 = "Water", type2 = "Steel" },
  {name = "Starly", type1 = "Normal", type2 = "Flying" },
  {name = "Staravia", type1 = "Normal", type2 = "Flying" },
  {name = "Staraptor", type1 = "Normal", type2 = "Flying" },
  {name = "Bidoof", type1 = "Normal", type2 = nil },
  {name = "Bibarel", type1 = "Normal", type2 = "Water" },
  {name = "Kricketot", type1 = "Bug", type2 = nil },
  {name = "Kricketune", type1 = "Bug", type2 = nil },
  {name = "Shinx", type1 = "Electric", type2 = nil },
  {name = "Luxio", type1 = "Electric", type2 = nil },
  {name = "Luxray", type1 = "Electric", type2 = nil },
  {name = "Budew", type1 = "Grass", type2 = "Poison" },
  {name = "Roserade", type1 = "Grass", type2 = "Poison" },
  {name = "Cranidos", type1 = "Rock", type2 = nil },
  {name = "Rampardos", type1 = "Rock", type2 = nil },
  {name = "Shieldon", type1 = "Rock", type2 = "Steel" },
  {name = "Bastiodon", type1 = "Rock", type2 = "Steel" },
  {name = "Burmy", type1 = "Bug", type2 = nil },
  {name = "Wormadam Plant", type1 = "Bug", type2 = "Grass" },
  {name = "Wormadam Sandy", type1 = "Bug", type2 = "Ground" },
  {name = "Wormadam Trash", type1 = "Bug", type2 = "Steel" },
  {name = "Mothim", type1 = "Bug", type2 = "Flying" },
  {name = "Combee", type1 = "Bug", type2 = "Flying" },
  {name = "Vespiquen", type1 = "Bug", type2 = "Flying" },
  {name = "Pachirisu", type1 = "Electric", type2 = nil },
  {name = "Buizel", type1 = "Water", type2 = nil },
  {name = "Floatzel", type1 = "Water", type2 = nil },
  {name = "Cherubi", type1 = "Grass", type2 = nil },
  {name = "Cherrim", type1 = "Grass", type2 = nil },
  {name = "Shellos", type1 = "Water", type2 = nil },
  {name = "Gastrodon", type1 = "Water", type2 = "Ground" },
  {name = "Ambipom", type1 = "Normal", type2 = nil },
  {name = "Drifloon", type1 = "Ghost", type2 = "Flying" },
  {name = "Drifblim", type1 = "Ghost", type2 = "Flying" },
  {name = "Buneary", type1 = "Normal", type2 = nil },
  {name = "Lopunny", type1 = "Normal", type2 = nil },
  {name = "Mismagius", type1 = "Ghost", type2 = nil },
  {name = "Honchkrow", type1 = "Dark", type2 = "Flying" },
  {name = "Glameow", type1 = "Normal", type2 = nil },
  {name = "Purugly", type1 = "Normal", type2 = nil },
  {name = "Stunky", type1 = "Poison", type2 = "Dark" },
  {name = "Skuntank", type1 = "Poison", type2 = "Dark" },
  {name = "Bronzor", type1 = "Steel", type2 = "Psychic" },
  {name = "Bronzong", type1 = "Steel", type2 = "Psychic" },
  {name = "Bonsly", type1 = "Rock", type2 = nil },
  {name = "Mime Jr.", type1 = "Psychic", type2 = "Fairy" },
  {name = "Happiny", type1 = "Normal", type2 = nil },
  {name = "Chatot", type1 = "Normal", type2 = "Flying" },
  {name = "Spiritomb", type1 = "Ghost", type2 = "Dark" },
  {name = "Gible", type1 = "Dragon", type2 = "Ground" },
  {name = "Gabite", type1 = "Dragon", type2 = "Ground" },
  {name = "Garchomp", type1 = "Dragon", type2 = "Ground" },
  {name = "Munchlax", type1 = "Normal", type2 = nil },
  {name = "Snorlax", type1 = "Normal", type2 = nil },
  {name = "Riolu", type1 = "Fighting", type2 = nil },
  {name = "Lucario", type1 = "Fighting", type2 = "Steel" },
  {name = "Hippopotas", type1 = "Ground", type2 = nil },
  {name = "Hippowdon", type1 = "Ground", type2 = nil },
  {name = "Skorupi", type1 = "Poison", type2 = "Bug" },
  {name = "Drapion", type1 = "Poison", type2 = "Dark" },
  {name = "Croagunk", type1 = "Poison", type2 = "Fighting" },
  {name = "Toxicroak", type1 = "Poison", type2 = "Fighting" },
  {name = "Carnivine", type1 = "Grass", type2 = nil },
  {name = "Finneon", type1 = "Water", type2 = nil },
  {name = "Lumineon", type1 = "Water", type2 = nil },
  {name = "Mantyke", type1 = "Water", type2 = "Flying" },
  {name = "Mantine", type1 = "Water", type2 = "Flying" },
  {name = "Phione", type1 = "Water", type2 = nil },
  {name = "Manaphy", type1 = "Water", type2 = nil },
  {name = "Darkrai", type1 = "Dark", type2 = nil },
  {name = "Shaymin", type1 = "Grass", type2 = nil },
  {name = "Arceus", type1 = "Normal", type2 = nil },
}

typeColors = {
  ["Normal"] = "#969493",
  ["Fire"] = "#db4347",
  ["Water"] = "#55b8e2",
  ["Electric"] = "#dcb40a",
  ["Grass"] = "#459e4e",
  ["Ice"] = "#6eb4b9",
  ["Fighting"] = "#d57944",
  ["Poison"] = "#74458e",
  ["Ground"] = "#9b5f41",
  ["Flying"] = "#5a82f0",
  ["Psychic"] = "#e66e9b",
  ["Bug"] = "#9cb558",
  ["Rock"] = "#a08c78",
  ["Ghost"] = "#a0739b",
  ["Dragon"] = "#1284a1",
  ["Dark"] = "#565562",
  ["Steel"] = "#7d879b",
  ["Fairy"] = "#ed9bb8",
}

typeBases = {
  ["Normal"] = "6",
  ["Fire"] = "3",
  ["Water"] = "7",
  ["Electric"] = "1",
  ["Grass"] = "4",
  ["Ice"] = "5",
  ["Fighting"] = "2",
  ["Poison"] = "4",
  ["Ground"] = "8",
  ["Flying"] = "6",
  ["Psychic"] = "9",
  ["Bug"] = "4",
  ["Rock"] = "10",
  ["Ghost"] = "11",
  ["Dragon"] = "6",
  ["Dark"] = "11",
  ["Steel"] = "2",
  ["Fairy"] = "4",
}

colors = {
  {19, "#FF0000"},  -- Vermelho
  {39, "#FFA500"},  -- Laranja
  {59, "#FFFF00"},  -- Amarelo
  {79, "#00FF00"},  -- Verde
  {100, "#0000FF"},  -- Azul
}
healthColors = {
  {0, "#B71C1C"},   -- Vermelho escuro
  {20, "#FF5722"},  -- Laranja
  {40, "#FFC107"},  -- Amarelo escuro
  {60, "#8BC34A"},  -- Verde claro
  {100, "#4CAF50"}  -- Verde escuro
}

function getTypesByName(name)
  for i, pokemon in ipairs(pokemonTypeTable) do
    if pokemon.name == name then
      return pokemon.type1, pokemon.type2
    end
  end
  return nil, nil
end

function getColorByType(type)
  return typeColors[type] or "#FFFFFF"
end
function getBaseByType(type)
  return typeBases[type] or "6"
end

function formatar_valor(valor)
  return string.format("%d", valor):reverse():gsub("%d%d%d", "%1."):reverse():gsub("^%.", "")
end

function getPokemonNumberByName(name)
  for i, pokemon in ipairs(pokemonTypeTable) do
    if pokemon.name == name then
      return string.format("%02d", i)
    end
  end
  return nil
end

function convertNumber(num)
  local units = {"", "k", "kk", "kkk", "kkkk", "kkkkk", "kkkkkk"}
  local numStr = tostring(num)
  local len = string.len(numStr)
  local remainder = len % 3
  local parts = {}
  
  if remainder > 0 then
    table.insert(parts, string.sub(numStr, 1, remainder))
  end
  
  for i=remainder+1, len, 3 do
    table.insert(parts, string.sub(numStr, i, i+2))
  end
  
  local result = ""
  for i=1, #parts do
    result = result .. parts[i] .. units[#parts - i + 1] .. " "
  end
  
  return string.sub(result, 1, -2) -- remove último espaço em branco
end

function getIVColor(ivPercentage)
  for i = 1, #colors do
    if ivPercentage <= colors[i][1] then
      return colors[i][2]
    end
  end
end

function getHealthColor(healthPercentage)
  for i = 1, #healthColors do
	if healthPercentage > 100 then
      return "#4CAF50"
    elseif healthPercentage <= healthColors[i][1] then
      return healthColors[i][2] or "#4CAF50"
    end
  end
end

function getPercentage(currentHealth, maxHealth)
  return math.floor((currentHealth / maxHealth) * 100 + 0.5)
end